version: '3.6'
# 3.6 pour windows
services:
  web:
     image: php:7.2-apache
     environment:
       - ALLOW_OVERRIDE=true
     ports:
       - "8042:80"
     links:
       - db
     volumes:
       - ./app:/var/www/html/
  db:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8891:80
    environment:
        - MYSQL_DATABASE=project
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root